server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


